// @generated by protoc-gen-connect-query v2.1.1 with parameter "target=ts,import_extension=none"
// @generated from file svc/release/v1/service.proto (package svc.release.v1, syntax proto3)
/* eslint-disable */

import { ReleaseService } from "./service_pb";

/**
 * @generated from rpc svc.release.v1.ReleaseService.CreateReleaseChannel
 */
export const createReleaseChannel = ReleaseService.method.createReleaseChannel;

/**
 * @generated from rpc svc.release.v1.ReleaseService.ListReleaseChannel
 */
export const listReleaseChannel = ReleaseService.method.listReleaseChannel;

/**
 * @generated from rpc svc.release.v1.ReleaseService.PublishVersion
 */
export const publishVersion = ReleaseService.method.publishVersion;

/**
 * @generated from rpc svc.release.v1.ReleaseService.UnpublishVersion
 */
export const unpublishVersion = ReleaseService.method.unpublishVersion;

/**
 * @generated from rpc svc.release.v1.ReleaseService.CreateVersionArtifact
 */
export const createVersionArtifact = ReleaseService.method.createVersionArtifact;

/**
 * @generated from rpc svc.release.v1.ReleaseService.DeleteVersionArtifact
 */
export const deleteVersionArtifact = ReleaseService.method.deleteVersionArtifact;

/**
 * @generated from rpc svc.release.v1.ReleaseService.ListVersionArtifact
 */
export const listVersionArtifact = ReleaseService.method.listVersionArtifact;
