// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file svc/auth/v1/service.proto (package svc.auth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BeginDeviceAuthRequest, BeginDeviceAuthResponse, CompleteDeviceAuthRequest, CompleteDeviceAuthResponse, GetAuthURLRequest, GetAuthURLResponse } from "./service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service svc.auth.v1.AuthService
 */
export const AuthService = {
  typeName: "svc.auth.v1.AuthService",
  methods: {
    /**
     * @generated from rpc svc.auth.v1.AuthService.GetAuthURL
     */
    getAuthURL: {
      name: "GetAuthURL",
      I: GetAuthURLRequest,
      O: GetAuthURLResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc svc.auth.v1.AuthService.BeginDeviceAuth
     */
    beginDeviceAuth: {
      name: "BeginDeviceAuth",
      I: BeginDeviceAuthRequest,
      O: BeginDeviceAuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc svc.auth.v1.AuthService.CompleteDeviceAuth
     */
    completeDeviceAuth: {
      name: "CompleteDeviceAuth",
      I: CompleteDeviceAuthRequest,
      O: CompleteDeviceAuthResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

