// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file svc/query/v1/service.proto (package svc.query.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SummarizeEventsRequest, SummarizeEventsResponse, WatchQueryRequest, WatchQueryResponse } from "./service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service svc.query.v1.QueryService
 */
export const QueryService = {
  typeName: "svc.query.v1.QueryService",
  methods: {
    /**
     * @generated from rpc svc.query.v1.QueryService.SummarizeEvents
     */
    summarizeEvents: {
      name: "SummarizeEvents",
      I: SummarizeEventsRequest,
      O: SummarizeEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc svc.query.v1.QueryService.WatchQuery
     */
    watchQuery: {
      name: "WatchQuery",
      I: WatchQueryRequest,
      O: WatchQueryResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

