// @generated by protoc-gen-connect-query v1.4.1 with parameter "target=ts,import_extension=none"
// @generated from file svc/query/v1/trace_service.proto (package svc.query.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { GetSpanRequest, GetSpanResponse, GetTraceRequest, GetTraceResponse } from "./trace_service_pb";

/**
 * @generated from rpc svc.query.v1.TraceService.GetTrace
 */
export const getTrace = {
  localName: "getTrace",
  name: "GetTrace",
  kind: MethodKind.Unary,
  I: GetTraceRequest,
  O: GetTraceResponse,
  service: {
    typeName: "svc.query.v1.TraceService"
  }
} as const;

/**
 * @generated from rpc svc.query.v1.TraceService.GetSpan
 */
export const getSpan = {
  localName: "getSpan",
  name: "GetSpan",
  kind: MethodKind.Unary,
  I: GetSpanRequest,
  O: GetSpanResponse,
  service: {
    typeName: "svc.query.v1.TraceService"
  }
} as const;
