// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/account_token.proto (package types.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum types.v1.AccountRole
 */
export enum AccountRole {
  /**
   * @generated from enum value: AccountRole_Invalid = 0;
   */
  AccountRole_Invalid = 0,

  /**
   * @generated from enum value: AccountRole_Ingestor = 1;
   */
  AccountRole_Ingestor = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(AccountRole)
proto3.util.setEnumType(AccountRole, "types.v1.AccountRole", [
  { no: 0, name: "AccountRole_Invalid" },
  { no: 1, name: "AccountRole_Ingestor" },
]);

/**
 * @generated from message types.v1.AccountToken
 */
export class AccountToken extends Message<AccountToken> {
  /**
   * @generated from field: int64 account_id = 1;
   */
  accountId = protoInt64.zero;

  /**
   * @generated from field: int64 token_id = 2;
   */
  tokenId = protoInt64.zero;

  /**
   * @generated from field: string token = 3;
   */
  token = "";

  /**
   * @generated from field: repeated types.v1.AccountRole roles = 4;
   */
  roles: AccountRole[] = [];

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 5;
   */
  expiresAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp revoked_at = 6;
   */
  revokedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp last_used_at = 7;
   */
  lastUsedAt?: Timestamp;

  constructor(data?: PartialMessage<AccountToken>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "types.v1.AccountToken";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "account_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "token_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "roles", kind: "enum", T: proto3.getEnumType(AccountRole), repeated: true },
    { no: 5, name: "expires_at", kind: "message", T: Timestamp },
    { no: 6, name: "revoked_at", kind: "message", T: Timestamp },
    { no: 7, name: "last_used_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AccountToken {
    return new AccountToken().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AccountToken {
    return new AccountToken().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AccountToken {
    return new AccountToken().fromJsonString(jsonString, options);
  }

  static equals(a: AccountToken | PlainMessage<AccountToken> | undefined, b: AccountToken | PlainMessage<AccountToken> | undefined): boolean {
    return proto3.util.equals(AccountToken, a, b);
  }
}

