// @generated by protoc-gen-es v2.9.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/project.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/project.proto.
 */
export const file_types_v1_project: GenFile = /*@__PURE__*/
  fileDesc("ChZ0eXBlcy92MS9wcm9qZWN0LnByb3RvEgh0eXBlcy52MSL/AgoOUHJvamVjdFBvaW50ZXISNAoGcmVtb3RlGAEgASgLMiIudHlwZXMudjEuUHJvamVjdFBvaW50ZXIuUmVtb3RlR2l0SAASNgoJbG9jYWxob3N0GAIgASgLMiEudHlwZXMudjEuUHJvamVjdFBvaW50ZXIuTG9jYWxHaXRIABIuCgJkYhgDIAEoCzIgLnR5cGVzLnYxLlByb2plY3RQb2ludGVyLlZpcnR1YWxIABpWCglSZW1vdGVHaXQSEgoKcmVtb3RlX3VybBgBIAEoCRILCgNyZWYYAiABKAkSFQoNZGFzaGJvYXJkX2RpchgDIAEoCRIRCglhbGVydF9kaXIYBCABKAkaVQoITG9jYWxHaXQSDAoEcGF0aBgBIAEoCRIVCg1kYXNoYm9hcmRfZGlyGAIgASgJEhEKCWFsZXJ0X2RpchgDIAEoCRIRCglyZWFkX29ubHkYBCABKAgaFgoHVmlydHVhbBILCgN1cmkYASABKAlCCAoGc2NoZW1lIqQBCgdQcm9qZWN0EgwKBG5hbWUYASABKAkSKQoHcG9pbnRlchgCIAEoCzIYLnR5cGVzLnYxLlByb2plY3RQb2ludGVyEi8KCmNyZWF0ZWRfYXQYrAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIvCgp1cGRhdGVkX2F0GK0CIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCjAEKDGNvbS50eXBlcy52MUIMUHJvamVjdFByb3RvUAFaLWdpdGh1Yi5jb20vaHVtYW5sb2dpby9hcGkvZ28vdHlwZXMvdjE7dHlwZXN2MaICA1RYWKoCCFR5cGVzLlYxygIIVHlwZXNcVjHiAhRUeXBlc1xWMVxHUEJNZXRhZGF0YeoCCVR5cGVzOjpWMWIGcHJvdG8z", [file_google_protobuf_duration, file_google_protobuf_timestamp]);

/**
 * @generated from message types.v1.ProjectPointer
 */
export type ProjectPointer = Message<"types.v1.ProjectPointer"> & {
  /**
   * @generated from oneof types.v1.ProjectPointer.scheme
   */
  scheme: {
    /**
     * @generated from field: types.v1.ProjectPointer.RemoteGit remote = 1;
     */
    value: ProjectPointer_RemoteGit;
    case: "remote";
  } | {
    /**
     * @generated from field: types.v1.ProjectPointer.LocalGit localhost = 2;
     */
    value: ProjectPointer_LocalGit;
    case: "localhost";
  } | {
    /**
     * @generated from field: types.v1.ProjectPointer.Virtual db = 3;
     */
    value: ProjectPointer_Virtual;
    case: "db";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message types.v1.ProjectPointer.
 * Use `create(ProjectPointerSchema)` to create a new message.
 */
export const ProjectPointerSchema: GenMessage<ProjectPointer> = /*@__PURE__*/
  messageDesc(file_types_v1_project, 0);

/**
 * @generated from message types.v1.ProjectPointer.RemoteGit
 */
export type ProjectPointer_RemoteGit = Message<"types.v1.ProjectPointer.RemoteGit"> & {
  /**
   * @generated from field: string remote_url = 1;
   */
  remoteUrl: string;

  /**
   * @generated from field: string ref = 2;
   */
  ref: string;

  /**
   * @generated from field: string dashboard_dir = 3;
   */
  dashboardDir: string;

  /**
   * @generated from field: string alert_dir = 4;
   */
  alertDir: string;
};

/**
 * Describes the message types.v1.ProjectPointer.RemoteGit.
 * Use `create(ProjectPointer_RemoteGitSchema)` to create a new message.
 */
export const ProjectPointer_RemoteGitSchema: GenMessage<ProjectPointer_RemoteGit> = /*@__PURE__*/
  messageDesc(file_types_v1_project, 0, 0);

/**
 * @generated from message types.v1.ProjectPointer.LocalGit
 */
export type ProjectPointer_LocalGit = Message<"types.v1.ProjectPointer.LocalGit"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: string dashboard_dir = 2;
   */
  dashboardDir: string;

  /**
   * @generated from field: string alert_dir = 3;
   */
  alertDir: string;

  /**
   * @generated from field: bool read_only = 4;
   */
  readOnly: boolean;
};

/**
 * Describes the message types.v1.ProjectPointer.LocalGit.
 * Use `create(ProjectPointer_LocalGitSchema)` to create a new message.
 */
export const ProjectPointer_LocalGitSchema: GenMessage<ProjectPointer_LocalGit> = /*@__PURE__*/
  messageDesc(file_types_v1_project, 0, 1);

/**
 * @generated from message types.v1.ProjectPointer.Virtual
 */
export type ProjectPointer_Virtual = Message<"types.v1.ProjectPointer.Virtual"> & {
  /**
   * @generated from field: string uri = 1;
   */
  uri: string;
};

/**
 * Describes the message types.v1.ProjectPointer.Virtual.
 * Use `create(ProjectPointer_VirtualSchema)` to create a new message.
 */
export const ProjectPointer_VirtualSchema: GenMessage<ProjectPointer_Virtual> = /*@__PURE__*/
  messageDesc(file_types_v1_project, 0, 2);

/**
 * @generated from message types.v1.Project
 */
export type Project = Message<"types.v1.Project"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: types.v1.ProjectPointer pointer = 2;
   */
  pointer?: ProjectPointer;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 300;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 301;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message types.v1.Project.
 * Use `create(ProjectSchema)` to create a new message.
 */
export const ProjectSchema: GenMessage<Project> = /*@__PURE__*/
  messageDesc(file_types_v1_project, 1);

