// @generated by protoc-gen-es v2.9.0 with parameter "target=ts,import_extension=none"
// @generated from file svc/product/v1/service.proto (package svc.product.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Cursor } from "../../../types/v1/cursor_pb";
import { file_types_v1_cursor } from "../../../types/v1/cursor_pb";
import type { Price } from "../../../types/v1/price_pb";
import { file_types_v1_price } from "../../../types/v1/price_pb";
import type { Product, Product_Scope } from "../../../types/v1/product_pb";
import { file_types_v1_product } from "../../../types/v1/product_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file svc/product/v1/service.proto.
 */
export const file_svc_product_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChxzdmMvcHJvZHVjdC92MS9zZXJ2aWNlLnByb3RvEg5zdmMucHJvZHVjdC52MSImChFHZXRQcm9kdWN0UmVxdWVzdBIRCglzdHJpcGVfaWQYASABKAkiWQoSR2V0UHJvZHVjdFJlc3BvbnNlEiIKB3Byb2R1Y3QYASABKAsyES50eXBlcy52MS5Qcm9kdWN0Eh8KBnByaWNlcxgCIAMoCzIPLnR5cGVzLnYxLlByaWNlIo8BChJMaXN0UHJvZHVjdFJlcXVlc3QSIAoGY3Vyc29yGAEgASgLMhAudHlwZXMudjEuQ3Vyc29yEg0KBWxpbWl0GAIgASgFEhAKCGNhdGVnb3J5GAMgASgJEiwKBXNjb3BlGJADIAEoDjIXLnR5cGVzLnYxLlByb2R1Y3QuU2NvcGVIAIgBAUIICgZfc2NvcGUi7wEKE0xpc3RQcm9kdWN0UmVzcG9uc2USHgoEbmV4dBgBIAEoCzIQLnR5cGVzLnYxLkN1cnNvchI7CgVpdGVtcxgCIAMoCzIsLnN2Yy5wcm9kdWN0LnYxLkxpc3RQcm9kdWN0UmVzcG9uc2UuTGlzdEl0ZW0SKgoPZGVmYXVsdF9wcm9kdWN0GAMgASgLMhEudHlwZXMudjEuUHJvZHVjdBpPCghMaXN0SXRlbRIiCgdwcm9kdWN0GAEgASgLMhEudHlwZXMudjEuUHJvZHVjdBIfCgZwcmljZXMYAiADKAsyDy50eXBlcy52MS5QcmljZTK9AQoOUHJvZHVjdFNlcnZpY2USUwoKR2V0UHJvZHVjdBIhLnN2Yy5wcm9kdWN0LnYxLkdldFByb2R1Y3RSZXF1ZXN0GiIuc3ZjLnByb2R1Y3QudjEuR2V0UHJvZHVjdFJlc3BvbnNlElYKC0xpc3RQcm9kdWN0EiIuc3ZjLnByb2R1Y3QudjEuTGlzdFByb2R1Y3RSZXF1ZXN0GiMuc3ZjLnByb2R1Y3QudjEuTGlzdFByb2R1Y3RSZXNwb25zZUKzAQoSY29tLnN2Yy5wcm9kdWN0LnYxQgxTZXJ2aWNlUHJvdG9QAVo1Z2l0aHViLmNvbS9odW1hbmxvZ2lvL2FwaS9nby9zdmMvcHJvZHVjdC92MTtwcm9kdWN0djGiAgNTUFiqAg5TdmMuUHJvZHVjdC5WMcoCDlN2Y1xQcm9kdWN0XFYx4gIaU3ZjXFByb2R1Y3RcVjFcR1BCTWV0YWRhdGHqAhBTdmM6OlByb2R1Y3Q6OlYxYgZwcm90bzM", [file_types_v1_cursor, file_types_v1_price, file_types_v1_product]);

/**
 * @generated from message svc.product.v1.GetProductRequest
 */
export type GetProductRequest = Message<"svc.product.v1.GetProductRequest"> & {
  /**
   * @generated from field: string stripe_id = 1;
   */
  stripeId: string;
};

/**
 * Describes the message svc.product.v1.GetProductRequest.
 * Use `create(GetProductRequestSchema)` to create a new message.
 */
export const GetProductRequestSchema: GenMessage<GetProductRequest> = /*@__PURE__*/
  messageDesc(file_svc_product_v1_service, 0);

/**
 * @generated from message svc.product.v1.GetProductResponse
 */
export type GetProductResponse = Message<"svc.product.v1.GetProductResponse"> & {
  /**
   * @generated from field: types.v1.Product product = 1;
   */
  product?: Product;

  /**
   * @generated from field: repeated types.v1.Price prices = 2;
   */
  prices: Price[];
};

/**
 * Describes the message svc.product.v1.GetProductResponse.
 * Use `create(GetProductResponseSchema)` to create a new message.
 */
export const GetProductResponseSchema: GenMessage<GetProductResponse> = /*@__PURE__*/
  messageDesc(file_svc_product_v1_service, 1);

/**
 * @generated from message svc.product.v1.ListProductRequest
 */
export type ListProductRequest = Message<"svc.product.v1.ListProductRequest"> & {
  /**
   * @generated from field: types.v1.Cursor cursor = 1;
   */
  cursor?: Cursor;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: string category = 3;
   */
  category: string;

  /**
   * filters
   *
   * @generated from field: optional types.v1.Product.Scope scope = 400;
   */
  scope?: Product_Scope;
};

/**
 * Describes the message svc.product.v1.ListProductRequest.
 * Use `create(ListProductRequestSchema)` to create a new message.
 */
export const ListProductRequestSchema: GenMessage<ListProductRequest> = /*@__PURE__*/
  messageDesc(file_svc_product_v1_service, 2);

/**
 * @generated from message svc.product.v1.ListProductResponse
 */
export type ListProductResponse = Message<"svc.product.v1.ListProductResponse"> & {
  /**
   * @generated from field: types.v1.Cursor next = 1;
   */
  next?: Cursor;

  /**
   * @generated from field: repeated svc.product.v1.ListProductResponse.ListItem items = 2;
   */
  items: ListProductResponse_ListItem[];

  /**
   * @generated from field: types.v1.Product default_product = 3;
   */
  defaultProduct?: Product;
};

/**
 * Describes the message svc.product.v1.ListProductResponse.
 * Use `create(ListProductResponseSchema)` to create a new message.
 */
export const ListProductResponseSchema: GenMessage<ListProductResponse> = /*@__PURE__*/
  messageDesc(file_svc_product_v1_service, 3);

/**
 * @generated from message svc.product.v1.ListProductResponse.ListItem
 */
export type ListProductResponse_ListItem = Message<"svc.product.v1.ListProductResponse.ListItem"> & {
  /**
   * @generated from field: types.v1.Product product = 1;
   */
  product?: Product;

  /**
   * @generated from field: repeated types.v1.Price prices = 2;
   */
  prices: Price[];
};

/**
 * Describes the message svc.product.v1.ListProductResponse.ListItem.
 * Use `create(ListProductResponse_ListItemSchema)` to create a new message.
 */
export const ListProductResponse_ListItemSchema: GenMessage<ListProductResponse_ListItem> = /*@__PURE__*/
  messageDesc(file_svc_product_v1_service, 3, 0);

/**
 * @generated from service svc.product.v1.ProductService
 */
export const ProductService: GenService<{
  /**
   * @generated from rpc svc.product.v1.ProductService.GetProduct
   */
  getProduct: {
    methodKind: "unary";
    input: typeof GetProductRequestSchema;
    output: typeof GetProductResponseSchema;
  },
  /**
   * @generated from rpc svc.product.v1.ProductService.ListProduct
   */
  listProduct: {
    methodKind: "unary";
    input: typeof ListProductRequestSchema;
    output: typeof ListProductResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_svc_product_v1_service, 0);

