// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file svc/product/v1/service.proto (package svc.product.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListProductRequest, ListProductResponse } from "./service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service svc.product.v1.ProductService
 */
export const ProductService = {
  typeName: "svc.product.v1.ProductService",
  methods: {
    /**
     * @generated from rpc svc.product.v1.ProductService.ListProduct
     */
    listProduct: {
      name: "ListProduct",
      I: ListProductRequest,
      O: ListProductResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

