#!/usr/bin/env bash

set -e

# eval "$(pkgx --shellcode)"
root=$(git rev-parse --show-toplevel)

function main() {
    pushd ${root}
    rm -r ${root}/js/*
    generate_protobuf
    pushd ${root}/go
    go mod tidy
}

function generate_protobuf() {
    export PATH=${PATH}:${root}/node_modules/.bin
    pkgx buf format -w
    pkgx buf dep update proto
    pkgx buf generate
}

main
