// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: svc/alert/v1/service.proto

package alertv1

import (
	v1 "github.com/humanlogio/api/go/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAlertGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,101,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	StackName     string                 `protobuf:"bytes,102,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Interval      *durationpb.Duration   `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	QueryOffset   *durationpb.Duration   `protobuf:"bytes,3,opt,name=query_offset,json=queryOffset,proto3" json:"query_offset,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Rules         []*v1.AlertRule        `protobuf:"bytes,5,rep,name=rules,proto3" json:"rules,omitempty"`
	Labels        *v1.Obj                `protobuf:"bytes,6,opt,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertGroupRequest) Reset() {
	*x = CreateAlertGroupRequest{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertGroupRequest) ProtoMessage() {}

func (x *CreateAlertGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertGroupRequest) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAlertGroupRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *CreateAlertGroupRequest) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *CreateAlertGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAlertGroupRequest) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *CreateAlertGroupRequest) GetQueryOffset() *durationpb.Duration {
	if x != nil {
		return x.QueryOffset
	}
	return nil
}

func (x *CreateAlertGroupRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CreateAlertGroupRequest) GetRules() []*v1.AlertRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *CreateAlertGroupRequest) GetLabels() *v1.Obj {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateAlertGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertGroup    *v1.AlertGroup         `protobuf:"bytes,1,opt,name=alert_group,json=alertGroup,proto3" json:"alert_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertGroupResponse) Reset() {
	*x = CreateAlertGroupResponse{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertGroupResponse) ProtoMessage() {}

func (x *CreateAlertGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateAlertGroupResponse) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAlertGroupResponse) GetAlertGroup() *v1.AlertGroup {
	if x != nil {
		return x.AlertGroup
	}
	return nil
}

type GetAlertGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,101,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	StackName     string                 `protobuf:"bytes,102,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertGroupRequest) Reset() {
	*x = GetAlertGroupRequest{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertGroupRequest) ProtoMessage() {}

func (x *GetAlertGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertGroupRequest.ProtoReflect.Descriptor instead.
func (*GetAlertGroupRequest) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAlertGroupRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *GetAlertGroupRequest) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *GetAlertGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAlertGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertGroup    *v1.AlertGroup         `protobuf:"bytes,1,opt,name=alert_group,json=alertGroup,proto3" json:"alert_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertGroupResponse) Reset() {
	*x = GetAlertGroupResponse{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertGroupResponse) ProtoMessage() {}

func (x *GetAlertGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertGroupResponse.ProtoReflect.Descriptor instead.
func (*GetAlertGroupResponse) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAlertGroupResponse) GetAlertGroup() *v1.AlertGroup {
	if x != nil {
		return x.AlertGroup
	}
	return nil
}

type UpdateAlertGroupRequest struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	EnvironmentId int64                               `protobuf:"varint,101,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	StackName     string                              `protobuf:"bytes,102,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	Name          string                              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mutations     []*UpdateAlertGroupRequest_Mutation `protobuf:"bytes,2,rep,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertGroupRequest) Reset() {
	*x = UpdateAlertGroupRequest{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertGroupRequest) ProtoMessage() {}

func (x *UpdateAlertGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlertGroupRequest) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAlertGroupRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *UpdateAlertGroupRequest) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *UpdateAlertGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAlertGroupRequest) GetMutations() []*UpdateAlertGroupRequest_Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

type UpdateAlertGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertGroup    *v1.AlertGroup         `protobuf:"bytes,1,opt,name=alert_group,json=alertGroup,proto3" json:"alert_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertGroupResponse) Reset() {
	*x = UpdateAlertGroupResponse{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertGroupResponse) ProtoMessage() {}

func (x *UpdateAlertGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateAlertGroupResponse) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAlertGroupResponse) GetAlertGroup() *v1.AlertGroup {
	if x != nil {
		return x.AlertGroup
	}
	return nil
}

type DeleteAlertGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,101,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	StackName     string                 `protobuf:"bytes,102,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertGroupRequest) Reset() {
	*x = DeleteAlertGroupRequest{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertGroupRequest) ProtoMessage() {}

func (x *DeleteAlertGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlertGroupRequest) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAlertGroupRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *DeleteAlertGroupRequest) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *DeleteAlertGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteAlertGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertGroupResponse) Reset() {
	*x = DeleteAlertGroupResponse{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertGroupResponse) ProtoMessage() {}

func (x *DeleteAlertGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteAlertGroupResponse) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{7}
}

type ListAlertGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,101,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	StackName     string                 `protobuf:"bytes,102,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertGroupRequest) Reset() {
	*x = ListAlertGroupRequest{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertGroupRequest) ProtoMessage() {}

func (x *ListAlertGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertGroupRequest.ProtoReflect.Descriptor instead.
func (*ListAlertGroupRequest) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListAlertGroupRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *ListAlertGroupRequest) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *ListAlertGroupRequest) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *ListAlertGroupRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListAlertGroupResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Next          *v1.Cursor                         `protobuf:"bytes,100,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*ListAlertGroupResponse_ListItem `protobuf:"bytes,200,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertGroupResponse) Reset() {
	*x = ListAlertGroupResponse{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertGroupResponse) ProtoMessage() {}

func (x *ListAlertGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertGroupResponse.ProtoReflect.Descriptor instead.
func (*ListAlertGroupResponse) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListAlertGroupResponse) GetNext() *v1.Cursor {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *ListAlertGroupResponse) GetItems() []*ListAlertGroupResponse_ListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,101,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	StackName     string                 `protobuf:"bytes,102,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	GroupName     string                 `protobuf:"bytes,103,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Expr          *v1.Query              `protobuf:"bytes,2,opt,name=expr,proto3" json:"expr,omitempty"`
	Labels        *v1.Obj                `protobuf:"bytes,3,opt,name=labels,proto3" json:"labels,omitempty"`
	Annotations   *v1.Obj                `protobuf:"bytes,4,opt,name=annotations,proto3" json:"annotations,omitempty"`
	For           *durationpb.Duration   `protobuf:"bytes,51,opt,name=for,proto3" json:"for,omitempty"`
	KeepFiringFor *durationpb.Duration   `protobuf:"bytes,52,opt,name=keep_firing_for,json=keepFiringFor,proto3" json:"keep_firing_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRuleRequest) Reset() {
	*x = CreateAlertRuleRequest{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRuleRequest) ProtoMessage() {}

func (x *CreateAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreateAlertRuleRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *CreateAlertRuleRequest) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetExpr() *v1.Query {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *CreateAlertRuleRequest) GetLabels() *v1.Obj {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateAlertRuleRequest) GetAnnotations() *v1.Obj {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *CreateAlertRuleRequest) GetFor() *durationpb.Duration {
	if x != nil {
		return x.For
	}
	return nil
}

func (x *CreateAlertRuleRequest) GetKeepFiringFor() *durationpb.Duration {
	if x != nil {
		return x.KeepFiringFor
	}
	return nil
}

type CreateAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertRule     *v1.AlertRule          `protobuf:"bytes,1,opt,name=alert_rule,json=alertRule,proto3" json:"alert_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRuleResponse) Reset() {
	*x = CreateAlertRuleResponse{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRuleResponse) ProtoMessage() {}

func (x *CreateAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateAlertRuleResponse) GetAlertRule() *v1.AlertRule {
	if x != nil {
		return x.AlertRule
	}
	return nil
}

type GetAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,101,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	StackName     string                 `protobuf:"bytes,102,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	GroupName     string                 `protobuf:"bytes,103,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRuleRequest) Reset() {
	*x = GetAlertRuleRequest{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRuleRequest) ProtoMessage() {}

func (x *GetAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetAlertRuleRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *GetAlertRuleRequest) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *GetAlertRuleRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GetAlertRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertRule     *v1.AlertRule          `protobuf:"bytes,1,opt,name=alert_rule,json=alertRule,proto3" json:"alert_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRuleResponse) Reset() {
	*x = GetAlertRuleResponse{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRuleResponse) ProtoMessage() {}

func (x *GetAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*GetAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetAlertRuleResponse) GetAlertRule() *v1.AlertRule {
	if x != nil {
		return x.AlertRule
	}
	return nil
}

type UpdateAlertRuleRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	EnvironmentId int64                              `protobuf:"varint,101,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	StackName     string                             `protobuf:"bytes,102,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	GroupName     string                             `protobuf:"bytes,103,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Name          string                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mutations     []*UpdateAlertRuleRequest_Mutation `protobuf:"bytes,2,rep,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertRuleRequest) Reset() {
	*x = UpdateAlertRuleRequest{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertRuleRequest) ProtoMessage() {}

func (x *UpdateAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateAlertRuleRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *UpdateAlertRuleRequest) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAlertRuleRequest) GetMutations() []*UpdateAlertRuleRequest_Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

type UpdateAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertRule     *v1.AlertRule          `protobuf:"bytes,1,opt,name=alert_rule,json=alertRule,proto3" json:"alert_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertRuleResponse) Reset() {
	*x = UpdateAlertRuleResponse{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertRuleResponse) ProtoMessage() {}

func (x *UpdateAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*UpdateAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateAlertRuleResponse) GetAlertRule() *v1.AlertRule {
	if x != nil {
		return x.AlertRule
	}
	return nil
}

type DeleteAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,101,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	StackName     string                 `protobuf:"bytes,102,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	GroupName     string                 `protobuf:"bytes,103,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertRuleRequest) Reset() {
	*x = DeleteAlertRuleRequest{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertRuleRequest) ProtoMessage() {}

func (x *DeleteAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteAlertRuleRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *DeleteAlertRuleRequest) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *DeleteAlertRuleRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *DeleteAlertRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertRuleResponse) Reset() {
	*x = DeleteAlertRuleResponse{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertRuleResponse) ProtoMessage() {}

func (x *DeleteAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{17}
}

type ListAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,101,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	StackName     string                 `protobuf:"bytes,102,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	GroupName     string                 `protobuf:"bytes,103,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Cursor        *v1.Cursor             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertRuleRequest) Reset() {
	*x = ListAlertRuleRequest{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertRuleRequest) ProtoMessage() {}

func (x *ListAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*ListAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{18}
}

func (x *ListAlertRuleRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *ListAlertRuleRequest) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *ListAlertRuleRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ListAlertRuleRequest) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *ListAlertRuleRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListAlertRuleResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Next          *v1.Cursor                        `protobuf:"bytes,100,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*ListAlertRuleResponse_ListItem `protobuf:"bytes,200,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertRuleResponse) Reset() {
	*x = ListAlertRuleResponse{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertRuleResponse) ProtoMessage() {}

func (x *ListAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*ListAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListAlertRuleResponse) GetNext() *v1.Cursor {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *ListAlertRuleResponse) GetItems() []*ListAlertRuleResponse_ListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateAlertGroupRequest_Mutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Do:
	//
	//	*UpdateAlertGroupRequest_Mutation_SetName
	//	*UpdateAlertGroupRequest_Mutation_SetInterval
	//	*UpdateAlertGroupRequest_Mutation_SetQueryOffset
	//	*UpdateAlertGroupRequest_Mutation_SetLimit
	//	*UpdateAlertGroupRequest_Mutation_SetLabels
	Do            isUpdateAlertGroupRequest_Mutation_Do `protobuf_oneof:"do"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertGroupRequest_Mutation) Reset() {
	*x = UpdateAlertGroupRequest_Mutation{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertGroupRequest_Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertGroupRequest_Mutation) ProtoMessage() {}

func (x *UpdateAlertGroupRequest_Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertGroupRequest_Mutation.ProtoReflect.Descriptor instead.
func (*UpdateAlertGroupRequest_Mutation) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UpdateAlertGroupRequest_Mutation) GetDo() isUpdateAlertGroupRequest_Mutation_Do {
	if x != nil {
		return x.Do
	}
	return nil
}

func (x *UpdateAlertGroupRequest_Mutation) GetSetName() string {
	if x != nil {
		if x, ok := x.Do.(*UpdateAlertGroupRequest_Mutation_SetName); ok {
			return x.SetName
		}
	}
	return ""
}

func (x *UpdateAlertGroupRequest_Mutation) GetSetInterval() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Do.(*UpdateAlertGroupRequest_Mutation_SetInterval); ok {
			return x.SetInterval
		}
	}
	return nil
}

func (x *UpdateAlertGroupRequest_Mutation) GetSetQueryOffset() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Do.(*UpdateAlertGroupRequest_Mutation_SetQueryOffset); ok {
			return x.SetQueryOffset
		}
	}
	return nil
}

func (x *UpdateAlertGroupRequest_Mutation) GetSetLimit() int32 {
	if x != nil {
		if x, ok := x.Do.(*UpdateAlertGroupRequest_Mutation_SetLimit); ok {
			return x.SetLimit
		}
	}
	return 0
}

func (x *UpdateAlertGroupRequest_Mutation) GetSetLabels() *v1.Obj {
	if x != nil {
		if x, ok := x.Do.(*UpdateAlertGroupRequest_Mutation_SetLabels); ok {
			return x.SetLabels
		}
	}
	return nil
}

type isUpdateAlertGroupRequest_Mutation_Do interface {
	isUpdateAlertGroupRequest_Mutation_Do()
}

type UpdateAlertGroupRequest_Mutation_SetName struct {
	SetName string `protobuf:"bytes,1,opt,name=set_name,json=setName,proto3,oneof"`
}

type UpdateAlertGroupRequest_Mutation_SetInterval struct {
	SetInterval *durationpb.Duration `protobuf:"bytes,2,opt,name=set_interval,json=setInterval,proto3,oneof"`
}

type UpdateAlertGroupRequest_Mutation_SetQueryOffset struct {
	SetQueryOffset *durationpb.Duration `protobuf:"bytes,3,opt,name=set_query_offset,json=setQueryOffset,proto3,oneof"`
}

type UpdateAlertGroupRequest_Mutation_SetLimit struct {
	SetLimit int32 `protobuf:"varint,4,opt,name=set_limit,json=setLimit,proto3,oneof"`
}

type UpdateAlertGroupRequest_Mutation_SetLabels struct {
	SetLabels *v1.Obj `protobuf:"bytes,5,opt,name=set_labels,json=setLabels,proto3,oneof"`
}

func (*UpdateAlertGroupRequest_Mutation_SetName) isUpdateAlertGroupRequest_Mutation_Do() {}

func (*UpdateAlertGroupRequest_Mutation_SetInterval) isUpdateAlertGroupRequest_Mutation_Do() {}

func (*UpdateAlertGroupRequest_Mutation_SetQueryOffset) isUpdateAlertGroupRequest_Mutation_Do() {}

func (*UpdateAlertGroupRequest_Mutation_SetLimit) isUpdateAlertGroupRequest_Mutation_Do() {}

func (*UpdateAlertGroupRequest_Mutation_SetLabels) isUpdateAlertGroupRequest_Mutation_Do() {}

type ListAlertGroupResponse_ListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertGroup    *v1.AlertGroup         `protobuf:"bytes,2,opt,name=alert_group,json=alertGroup,proto3" json:"alert_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertGroupResponse_ListItem) Reset() {
	*x = ListAlertGroupResponse_ListItem{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertGroupResponse_ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertGroupResponse_ListItem) ProtoMessage() {}

func (x *ListAlertGroupResponse_ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertGroupResponse_ListItem.ProtoReflect.Descriptor instead.
func (*ListAlertGroupResponse_ListItem) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ListAlertGroupResponse_ListItem) GetAlertGroup() *v1.AlertGroup {
	if x != nil {
		return x.AlertGroup
	}
	return nil
}

type UpdateAlertRuleRequest_Mutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Do:
	//
	//	*UpdateAlertRuleRequest_Mutation_SetName
	//	*UpdateAlertRuleRequest_Mutation_SetExpr
	//	*UpdateAlertRuleRequest_Mutation_SetLabels
	//	*UpdateAlertRuleRequest_Mutation_SetAnnotations
	//	*UpdateAlertRuleRequest_Mutation_SetFor
	//	*UpdateAlertRuleRequest_Mutation_SetKeepFiringFor
	Do            isUpdateAlertRuleRequest_Mutation_Do `protobuf_oneof:"do"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertRuleRequest_Mutation) Reset() {
	*x = UpdateAlertRuleRequest_Mutation{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertRuleRequest_Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertRuleRequest_Mutation) ProtoMessage() {}

func (x *UpdateAlertRuleRequest_Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertRuleRequest_Mutation.ProtoReflect.Descriptor instead.
func (*UpdateAlertRuleRequest_Mutation) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{14, 0}
}

func (x *UpdateAlertRuleRequest_Mutation) GetDo() isUpdateAlertRuleRequest_Mutation_Do {
	if x != nil {
		return x.Do
	}
	return nil
}

func (x *UpdateAlertRuleRequest_Mutation) GetSetName() string {
	if x != nil {
		if x, ok := x.Do.(*UpdateAlertRuleRequest_Mutation_SetName); ok {
			return x.SetName
		}
	}
	return ""
}

func (x *UpdateAlertRuleRequest_Mutation) GetSetExpr() *v1.Query {
	if x != nil {
		if x, ok := x.Do.(*UpdateAlertRuleRequest_Mutation_SetExpr); ok {
			return x.SetExpr
		}
	}
	return nil
}

func (x *UpdateAlertRuleRequest_Mutation) GetSetLabels() *v1.Obj {
	if x != nil {
		if x, ok := x.Do.(*UpdateAlertRuleRequest_Mutation_SetLabels); ok {
			return x.SetLabels
		}
	}
	return nil
}

func (x *UpdateAlertRuleRequest_Mutation) GetSetAnnotations() *v1.Obj {
	if x != nil {
		if x, ok := x.Do.(*UpdateAlertRuleRequest_Mutation_SetAnnotations); ok {
			return x.SetAnnotations
		}
	}
	return nil
}

func (x *UpdateAlertRuleRequest_Mutation) GetSetFor() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Do.(*UpdateAlertRuleRequest_Mutation_SetFor); ok {
			return x.SetFor
		}
	}
	return nil
}

func (x *UpdateAlertRuleRequest_Mutation) GetSetKeepFiringFor() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Do.(*UpdateAlertRuleRequest_Mutation_SetKeepFiringFor); ok {
			return x.SetKeepFiringFor
		}
	}
	return nil
}

type isUpdateAlertRuleRequest_Mutation_Do interface {
	isUpdateAlertRuleRequest_Mutation_Do()
}

type UpdateAlertRuleRequest_Mutation_SetName struct {
	SetName string `protobuf:"bytes,1,opt,name=set_name,json=setName,proto3,oneof"`
}

type UpdateAlertRuleRequest_Mutation_SetExpr struct {
	SetExpr *v1.Query `protobuf:"bytes,2,opt,name=set_expr,json=setExpr,proto3,oneof"`
}

type UpdateAlertRuleRequest_Mutation_SetLabels struct {
	SetLabels *v1.Obj `protobuf:"bytes,3,opt,name=set_labels,json=setLabels,proto3,oneof"`
}

type UpdateAlertRuleRequest_Mutation_SetAnnotations struct {
	SetAnnotations *v1.Obj `protobuf:"bytes,4,opt,name=set_annotations,json=setAnnotations,proto3,oneof"`
}

type UpdateAlertRuleRequest_Mutation_SetFor struct {
	SetFor *durationpb.Duration `protobuf:"bytes,51,opt,name=set_for,json=setFor,proto3,oneof"`
}

type UpdateAlertRuleRequest_Mutation_SetKeepFiringFor struct {
	SetKeepFiringFor *durationpb.Duration `protobuf:"bytes,52,opt,name=set_keep_firing_for,json=setKeepFiringFor,proto3,oneof"`
}

func (*UpdateAlertRuleRequest_Mutation_SetName) isUpdateAlertRuleRequest_Mutation_Do() {}

func (*UpdateAlertRuleRequest_Mutation_SetExpr) isUpdateAlertRuleRequest_Mutation_Do() {}

func (*UpdateAlertRuleRequest_Mutation_SetLabels) isUpdateAlertRuleRequest_Mutation_Do() {}

func (*UpdateAlertRuleRequest_Mutation_SetAnnotations) isUpdateAlertRuleRequest_Mutation_Do() {}

func (*UpdateAlertRuleRequest_Mutation_SetFor) isUpdateAlertRuleRequest_Mutation_Do() {}

func (*UpdateAlertRuleRequest_Mutation_SetKeepFiringFor) isUpdateAlertRuleRequest_Mutation_Do() {}

type ListAlertRuleResponse_ListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertRule     *v1.AlertRule          `protobuf:"bytes,1,opt,name=alert_rule,json=alertRule,proto3" json:"alert_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertRuleResponse_ListItem) Reset() {
	*x = ListAlertRuleResponse_ListItem{}
	mi := &file_svc_alert_v1_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertRuleResponse_ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertRuleResponse_ListItem) ProtoMessage() {}

func (x *ListAlertRuleResponse_ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_svc_alert_v1_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertRuleResponse_ListItem.ProtoReflect.Descriptor instead.
func (*ListAlertRuleResponse_ListItem) Descriptor() ([]byte, []int) {
	return file_svc_alert_v1_service_proto_rawDescGZIP(), []int{19, 0}
}

func (x *ListAlertRuleResponse_ListItem) GetAlertRule() *v1.AlertRule {
	if x != nil {
		return x.AlertRule
	}
	return nil
}

var File_svc_alert_v1_service_proto protoreflect.FileDescriptor

const file_svc_alert_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1asvc/alert/v1/service.proto\x12\fsvc.alert.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14types/v1/alert.proto\x1a\x15types/v1/cursor.proto\x1a\x14types/v1/query.proto\x1a\x14types/v1/types.proto\"\xd0\x02\n" +
	"\x17CreateAlertGroupRequest\x12%\n" +
	"\x0eenvironment_id\x18e \x01(\x03R\renvironmentId\x12\x1d\n" +
	"\n" +
	"stack_name\x18f \x01(\tR\tstackName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\binterval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\binterval\x12<\n" +
	"\fquery_offset\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vqueryOffset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12)\n" +
	"\x05rules\x18\x05 \x03(\v2\x13.types.v1.AlertRuleR\x05rules\x12%\n" +
	"\x06labels\x18\x06 \x01(\v2\r.types.v1.ObjR\x06labels\"Q\n" +
	"\x18CreateAlertGroupResponse\x125\n" +
	"\valert_group\x18\x01 \x01(\v2\x14.types.v1.AlertGroupR\n" +
	"alertGroup\"p\n" +
	"\x14GetAlertGroupRequest\x12%\n" +
	"\x0eenvironment_id\x18e \x01(\x03R\renvironmentId\x12\x1d\n" +
	"\n" +
	"stack_name\x18f \x01(\tR\tstackName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"N\n" +
	"\x15GetAlertGroupResponse\x125\n" +
	"\valert_group\x18\x01 \x01(\v2\x14.types.v1.AlertGroupR\n" +
	"alertGroup\"\xc7\x03\n" +
	"\x17UpdateAlertGroupRequest\x12%\n" +
	"\x0eenvironment_id\x18e \x01(\x03R\renvironmentId\x12\x1d\n" +
	"\n" +
	"stack_name\x18f \x01(\tR\tstackName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12L\n" +
	"\tmutations\x18\x02 \x03(\v2..svc.alert.v1.UpdateAlertGroupRequest.MutationR\tmutations\x1a\x83\x02\n" +
	"\bMutation\x12\x1b\n" +
	"\bset_name\x18\x01 \x01(\tH\x00R\asetName\x12>\n" +
	"\fset_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x00R\vsetInterval\x12E\n" +
	"\x10set_query_offset\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x00R\x0esetQueryOffset\x12\x1d\n" +
	"\tset_limit\x18\x04 \x01(\x05H\x00R\bsetLimit\x12.\n" +
	"\n" +
	"set_labels\x18\x05 \x01(\v2\r.types.v1.ObjH\x00R\tsetLabelsB\x04\n" +
	"\x02do\"Q\n" +
	"\x18UpdateAlertGroupResponse\x125\n" +
	"\valert_group\x18\x01 \x01(\v2\x14.types.v1.AlertGroupR\n" +
	"alertGroup\"s\n" +
	"\x17DeleteAlertGroupRequest\x12%\n" +
	"\x0eenvironment_id\x18e \x01(\x03R\renvironmentId\x12\x1d\n" +
	"\n" +
	"stack_name\x18f \x01(\tR\tstackName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1a\n" +
	"\x18DeleteAlertGroupResponse\"\x9d\x01\n" +
	"\x15ListAlertGroupRequest\x12%\n" +
	"\x0eenvironment_id\x18e \x01(\x03R\renvironmentId\x12\x1d\n" +
	"\n" +
	"stack_name\x18f \x01(\tR\tstackName\x12(\n" +
	"\x06cursor\x18\x02 \x01(\v2\x10.types.v1.CursorR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xc7\x01\n" +
	"\x16ListAlertGroupResponse\x12$\n" +
	"\x04next\x18d \x01(\v2\x10.types.v1.CursorR\x04next\x12D\n" +
	"\x05items\x18\xc8\x01 \x03(\v2-.svc.alert.v1.ListAlertGroupResponse.ListItemR\x05items\x1aA\n" +
	"\bListItem\x125\n" +
	"\valert_group\x18\x02 \x01(\v2\x14.types.v1.AlertGroupR\n" +
	"alertGroup\"\xfe\x02\n" +
	"\x16CreateAlertRuleRequest\x12%\n" +
	"\x0eenvironment_id\x18e \x01(\x03R\renvironmentId\x12\x1d\n" +
	"\n" +
	"stack_name\x18f \x01(\tR\tstackName\x12\x1d\n" +
	"\n" +
	"group_name\x18g \x01(\tR\tgroupName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\x04expr\x18\x02 \x01(\v2\x0f.types.v1.QueryR\x04expr\x12%\n" +
	"\x06labels\x18\x03 \x01(\v2\r.types.v1.ObjR\x06labels\x12/\n" +
	"\vannotations\x18\x04 \x01(\v2\r.types.v1.ObjR\vannotations\x12+\n" +
	"\x03for\x183 \x01(\v2\x19.google.protobuf.DurationR\x03for\x12A\n" +
	"\x0fkeep_firing_for\x184 \x01(\v2\x19.google.protobuf.DurationR\rkeepFiringFor\"M\n" +
	"\x17CreateAlertRuleResponse\x122\n" +
	"\n" +
	"alert_rule\x18\x01 \x01(\v2\x13.types.v1.AlertRuleR\talertRule\"\x8e\x01\n" +
	"\x13GetAlertRuleRequest\x12%\n" +
	"\x0eenvironment_id\x18e \x01(\x03R\renvironmentId\x12\x1d\n" +
	"\n" +
	"stack_name\x18f \x01(\tR\tstackName\x12\x1d\n" +
	"\n" +
	"group_name\x18g \x01(\tR\tgroupName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"J\n" +
	"\x14GetAlertRuleResponse\x122\n" +
	"\n" +
	"alert_rule\x18\x01 \x01(\v2\x13.types.v1.AlertRuleR\talertRule\"\xa8\x04\n" +
	"\x16UpdateAlertRuleRequest\x12%\n" +
	"\x0eenvironment_id\x18e \x01(\x03R\renvironmentId\x12\x1d\n" +
	"\n" +
	"stack_name\x18f \x01(\tR\tstackName\x12\x1d\n" +
	"\n" +
	"group_name\x18g \x01(\tR\tgroupName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12K\n" +
	"\tmutations\x18\x02 \x03(\v2-.svc.alert.v1.UpdateAlertRuleRequest.MutationR\tmutations\x1a\xc7\x02\n" +
	"\bMutation\x12\x1b\n" +
	"\bset_name\x18\x01 \x01(\tH\x00R\asetName\x12,\n" +
	"\bset_expr\x18\x02 \x01(\v2\x0f.types.v1.QueryH\x00R\asetExpr\x12.\n" +
	"\n" +
	"set_labels\x18\x03 \x01(\v2\r.types.v1.ObjH\x00R\tsetLabels\x128\n" +
	"\x0fset_annotations\x18\x04 \x01(\v2\r.types.v1.ObjH\x00R\x0esetAnnotations\x124\n" +
	"\aset_for\x183 \x01(\v2\x19.google.protobuf.DurationH\x00R\x06setFor\x12J\n" +
	"\x13set_keep_firing_for\x184 \x01(\v2\x19.google.protobuf.DurationH\x00R\x10setKeepFiringForB\x04\n" +
	"\x02do\"M\n" +
	"\x17UpdateAlertRuleResponse\x122\n" +
	"\n" +
	"alert_rule\x18\x01 \x01(\v2\x13.types.v1.AlertRuleR\talertRule\"\x91\x01\n" +
	"\x16DeleteAlertRuleRequest\x12%\n" +
	"\x0eenvironment_id\x18e \x01(\x03R\renvironmentId\x12\x1d\n" +
	"\n" +
	"stack_name\x18f \x01(\tR\tstackName\x12\x1d\n" +
	"\n" +
	"group_name\x18g \x01(\tR\tgroupName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x19\n" +
	"\x17DeleteAlertRuleResponse\"\xbb\x01\n" +
	"\x14ListAlertRuleRequest\x12%\n" +
	"\x0eenvironment_id\x18e \x01(\x03R\renvironmentId\x12\x1d\n" +
	"\n" +
	"stack_name\x18f \x01(\tR\tstackName\x12\x1d\n" +
	"\n" +
	"group_name\x18g \x01(\tR\tgroupName\x12(\n" +
	"\x06cursor\x18\x02 \x01(\v2\x10.types.v1.CursorR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xc2\x01\n" +
	"\x15ListAlertRuleResponse\x12$\n" +
	"\x04next\x18d \x01(\v2\x10.types.v1.CursorR\x04next\x12C\n" +
	"\x05items\x18\xc8\x01 \x03(\v2,.svc.alert.v1.ListAlertRuleResponse.ListItemR\x05items\x1a>\n" +
	"\bListItem\x122\n" +
	"\n" +
	"alert_rule\x18\x01 \x01(\v2\x13.types.v1.AlertRuleR\talertRule2\xbf\a\n" +
	"\fAlertService\x12a\n" +
	"\x10CreateAlertGroup\x12%.svc.alert.v1.CreateAlertGroupRequest\x1a&.svc.alert.v1.CreateAlertGroupResponse\x12X\n" +
	"\rGetAlertGroup\x12\".svc.alert.v1.GetAlertGroupRequest\x1a#.svc.alert.v1.GetAlertGroupResponse\x12a\n" +
	"\x10UpdateAlertGroup\x12%.svc.alert.v1.UpdateAlertGroupRequest\x1a&.svc.alert.v1.UpdateAlertGroupResponse\x12a\n" +
	"\x10DeleteAlertGroup\x12%.svc.alert.v1.DeleteAlertGroupRequest\x1a&.svc.alert.v1.DeleteAlertGroupResponse\x12[\n" +
	"\x0eListAlertGroup\x12#.svc.alert.v1.ListAlertGroupRequest\x1a$.svc.alert.v1.ListAlertGroupResponse\x12^\n" +
	"\x0fCreateAlertRule\x12$.svc.alert.v1.CreateAlertRuleRequest\x1a%.svc.alert.v1.CreateAlertRuleResponse\x12U\n" +
	"\fGetAlertRule\x12!.svc.alert.v1.GetAlertRuleRequest\x1a\".svc.alert.v1.GetAlertRuleResponse\x12^\n" +
	"\x0fUpdateAlertRule\x12$.svc.alert.v1.UpdateAlertRuleRequest\x1a%.svc.alert.v1.UpdateAlertRuleResponse\x12^\n" +
	"\x0fDeleteAlertRule\x12$.svc.alert.v1.DeleteAlertRuleRequest\x1a%.svc.alert.v1.DeleteAlertRuleResponse\x12X\n" +
	"\rListAlertRule\x12\".svc.alert.v1.ListAlertRuleRequest\x1a#.svc.alert.v1.ListAlertRuleResponseB\xa5\x01\n" +
	"\x10com.svc.alert.v1B\fServiceProtoP\x01Z1github.com/humanlogio/api/go/svc/alert/v1;alertv1\xa2\x02\x03SAX\xaa\x02\fSvc.Alert.V1\xca\x02\fSvc\\Alert\\V1\xe2\x02\x18Svc\\Alert\\V1\\GPBMetadata\xea\x02\x0eSvc::Alert::V1b\x06proto3"

var (
	file_svc_alert_v1_service_proto_rawDescOnce sync.Once
	file_svc_alert_v1_service_proto_rawDescData []byte
)

func file_svc_alert_v1_service_proto_rawDescGZIP() []byte {
	file_svc_alert_v1_service_proto_rawDescOnce.Do(func() {
		file_svc_alert_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_svc_alert_v1_service_proto_rawDesc), len(file_svc_alert_v1_service_proto_rawDesc)))
	})
	return file_svc_alert_v1_service_proto_rawDescData
}

var file_svc_alert_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_svc_alert_v1_service_proto_goTypes = []any{
	(*CreateAlertGroupRequest)(nil),          // 0: svc.alert.v1.CreateAlertGroupRequest
	(*CreateAlertGroupResponse)(nil),         // 1: svc.alert.v1.CreateAlertGroupResponse
	(*GetAlertGroupRequest)(nil),             // 2: svc.alert.v1.GetAlertGroupRequest
	(*GetAlertGroupResponse)(nil),            // 3: svc.alert.v1.GetAlertGroupResponse
	(*UpdateAlertGroupRequest)(nil),          // 4: svc.alert.v1.UpdateAlertGroupRequest
	(*UpdateAlertGroupResponse)(nil),         // 5: svc.alert.v1.UpdateAlertGroupResponse
	(*DeleteAlertGroupRequest)(nil),          // 6: svc.alert.v1.DeleteAlertGroupRequest
	(*DeleteAlertGroupResponse)(nil),         // 7: svc.alert.v1.DeleteAlertGroupResponse
	(*ListAlertGroupRequest)(nil),            // 8: svc.alert.v1.ListAlertGroupRequest
	(*ListAlertGroupResponse)(nil),           // 9: svc.alert.v1.ListAlertGroupResponse
	(*CreateAlertRuleRequest)(nil),           // 10: svc.alert.v1.CreateAlertRuleRequest
	(*CreateAlertRuleResponse)(nil),          // 11: svc.alert.v1.CreateAlertRuleResponse
	(*GetAlertRuleRequest)(nil),              // 12: svc.alert.v1.GetAlertRuleRequest
	(*GetAlertRuleResponse)(nil),             // 13: svc.alert.v1.GetAlertRuleResponse
	(*UpdateAlertRuleRequest)(nil),           // 14: svc.alert.v1.UpdateAlertRuleRequest
	(*UpdateAlertRuleResponse)(nil),          // 15: svc.alert.v1.UpdateAlertRuleResponse
	(*DeleteAlertRuleRequest)(nil),           // 16: svc.alert.v1.DeleteAlertRuleRequest
	(*DeleteAlertRuleResponse)(nil),          // 17: svc.alert.v1.DeleteAlertRuleResponse
	(*ListAlertRuleRequest)(nil),             // 18: svc.alert.v1.ListAlertRuleRequest
	(*ListAlertRuleResponse)(nil),            // 19: svc.alert.v1.ListAlertRuleResponse
	(*UpdateAlertGroupRequest_Mutation)(nil), // 20: svc.alert.v1.UpdateAlertGroupRequest.Mutation
	(*ListAlertGroupResponse_ListItem)(nil),  // 21: svc.alert.v1.ListAlertGroupResponse.ListItem
	(*UpdateAlertRuleRequest_Mutation)(nil),  // 22: svc.alert.v1.UpdateAlertRuleRequest.Mutation
	(*ListAlertRuleResponse_ListItem)(nil),   // 23: svc.alert.v1.ListAlertRuleResponse.ListItem
	(*durationpb.Duration)(nil),              // 24: google.protobuf.Duration
	(*v1.AlertRule)(nil),                     // 25: types.v1.AlertRule
	(*v1.Obj)(nil),                           // 26: types.v1.Obj
	(*v1.AlertGroup)(nil),                    // 27: types.v1.AlertGroup
	(*v1.Cursor)(nil),                        // 28: types.v1.Cursor
	(*v1.Query)(nil),                         // 29: types.v1.Query
}
var file_svc_alert_v1_service_proto_depIdxs = []int32{
	24, // 0: svc.alert.v1.CreateAlertGroupRequest.interval:type_name -> google.protobuf.Duration
	24, // 1: svc.alert.v1.CreateAlertGroupRequest.query_offset:type_name -> google.protobuf.Duration
	25, // 2: svc.alert.v1.CreateAlertGroupRequest.rules:type_name -> types.v1.AlertRule
	26, // 3: svc.alert.v1.CreateAlertGroupRequest.labels:type_name -> types.v1.Obj
	27, // 4: svc.alert.v1.CreateAlertGroupResponse.alert_group:type_name -> types.v1.AlertGroup
	27, // 5: svc.alert.v1.GetAlertGroupResponse.alert_group:type_name -> types.v1.AlertGroup
	20, // 6: svc.alert.v1.UpdateAlertGroupRequest.mutations:type_name -> svc.alert.v1.UpdateAlertGroupRequest.Mutation
	27, // 7: svc.alert.v1.UpdateAlertGroupResponse.alert_group:type_name -> types.v1.AlertGroup
	28, // 8: svc.alert.v1.ListAlertGroupRequest.cursor:type_name -> types.v1.Cursor
	28, // 9: svc.alert.v1.ListAlertGroupResponse.next:type_name -> types.v1.Cursor
	21, // 10: svc.alert.v1.ListAlertGroupResponse.items:type_name -> svc.alert.v1.ListAlertGroupResponse.ListItem
	29, // 11: svc.alert.v1.CreateAlertRuleRequest.expr:type_name -> types.v1.Query
	26, // 12: svc.alert.v1.CreateAlertRuleRequest.labels:type_name -> types.v1.Obj
	26, // 13: svc.alert.v1.CreateAlertRuleRequest.annotations:type_name -> types.v1.Obj
	24, // 14: svc.alert.v1.CreateAlertRuleRequest.for:type_name -> google.protobuf.Duration
	24, // 15: svc.alert.v1.CreateAlertRuleRequest.keep_firing_for:type_name -> google.protobuf.Duration
	25, // 16: svc.alert.v1.CreateAlertRuleResponse.alert_rule:type_name -> types.v1.AlertRule
	25, // 17: svc.alert.v1.GetAlertRuleResponse.alert_rule:type_name -> types.v1.AlertRule
	22, // 18: svc.alert.v1.UpdateAlertRuleRequest.mutations:type_name -> svc.alert.v1.UpdateAlertRuleRequest.Mutation
	25, // 19: svc.alert.v1.UpdateAlertRuleResponse.alert_rule:type_name -> types.v1.AlertRule
	28, // 20: svc.alert.v1.ListAlertRuleRequest.cursor:type_name -> types.v1.Cursor
	28, // 21: svc.alert.v1.ListAlertRuleResponse.next:type_name -> types.v1.Cursor
	23, // 22: svc.alert.v1.ListAlertRuleResponse.items:type_name -> svc.alert.v1.ListAlertRuleResponse.ListItem
	24, // 23: svc.alert.v1.UpdateAlertGroupRequest.Mutation.set_interval:type_name -> google.protobuf.Duration
	24, // 24: svc.alert.v1.UpdateAlertGroupRequest.Mutation.set_query_offset:type_name -> google.protobuf.Duration
	26, // 25: svc.alert.v1.UpdateAlertGroupRequest.Mutation.set_labels:type_name -> types.v1.Obj
	27, // 26: svc.alert.v1.ListAlertGroupResponse.ListItem.alert_group:type_name -> types.v1.AlertGroup
	29, // 27: svc.alert.v1.UpdateAlertRuleRequest.Mutation.set_expr:type_name -> types.v1.Query
	26, // 28: svc.alert.v1.UpdateAlertRuleRequest.Mutation.set_labels:type_name -> types.v1.Obj
	26, // 29: svc.alert.v1.UpdateAlertRuleRequest.Mutation.set_annotations:type_name -> types.v1.Obj
	24, // 30: svc.alert.v1.UpdateAlertRuleRequest.Mutation.set_for:type_name -> google.protobuf.Duration
	24, // 31: svc.alert.v1.UpdateAlertRuleRequest.Mutation.set_keep_firing_for:type_name -> google.protobuf.Duration
	25, // 32: svc.alert.v1.ListAlertRuleResponse.ListItem.alert_rule:type_name -> types.v1.AlertRule
	0,  // 33: svc.alert.v1.AlertService.CreateAlertGroup:input_type -> svc.alert.v1.CreateAlertGroupRequest
	2,  // 34: svc.alert.v1.AlertService.GetAlertGroup:input_type -> svc.alert.v1.GetAlertGroupRequest
	4,  // 35: svc.alert.v1.AlertService.UpdateAlertGroup:input_type -> svc.alert.v1.UpdateAlertGroupRequest
	6,  // 36: svc.alert.v1.AlertService.DeleteAlertGroup:input_type -> svc.alert.v1.DeleteAlertGroupRequest
	8,  // 37: svc.alert.v1.AlertService.ListAlertGroup:input_type -> svc.alert.v1.ListAlertGroupRequest
	10, // 38: svc.alert.v1.AlertService.CreateAlertRule:input_type -> svc.alert.v1.CreateAlertRuleRequest
	12, // 39: svc.alert.v1.AlertService.GetAlertRule:input_type -> svc.alert.v1.GetAlertRuleRequest
	14, // 40: svc.alert.v1.AlertService.UpdateAlertRule:input_type -> svc.alert.v1.UpdateAlertRuleRequest
	16, // 41: svc.alert.v1.AlertService.DeleteAlertRule:input_type -> svc.alert.v1.DeleteAlertRuleRequest
	18, // 42: svc.alert.v1.AlertService.ListAlertRule:input_type -> svc.alert.v1.ListAlertRuleRequest
	1,  // 43: svc.alert.v1.AlertService.CreateAlertGroup:output_type -> svc.alert.v1.CreateAlertGroupResponse
	3,  // 44: svc.alert.v1.AlertService.GetAlertGroup:output_type -> svc.alert.v1.GetAlertGroupResponse
	5,  // 45: svc.alert.v1.AlertService.UpdateAlertGroup:output_type -> svc.alert.v1.UpdateAlertGroupResponse
	7,  // 46: svc.alert.v1.AlertService.DeleteAlertGroup:output_type -> svc.alert.v1.DeleteAlertGroupResponse
	9,  // 47: svc.alert.v1.AlertService.ListAlertGroup:output_type -> svc.alert.v1.ListAlertGroupResponse
	11, // 48: svc.alert.v1.AlertService.CreateAlertRule:output_type -> svc.alert.v1.CreateAlertRuleResponse
	13, // 49: svc.alert.v1.AlertService.GetAlertRule:output_type -> svc.alert.v1.GetAlertRuleResponse
	15, // 50: svc.alert.v1.AlertService.UpdateAlertRule:output_type -> svc.alert.v1.UpdateAlertRuleResponse
	17, // 51: svc.alert.v1.AlertService.DeleteAlertRule:output_type -> svc.alert.v1.DeleteAlertRuleResponse
	19, // 52: svc.alert.v1.AlertService.ListAlertRule:output_type -> svc.alert.v1.ListAlertRuleResponse
	43, // [43:53] is the sub-list for method output_type
	33, // [33:43] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_svc_alert_v1_service_proto_init() }
func file_svc_alert_v1_service_proto_init() {
	if File_svc_alert_v1_service_proto != nil {
		return
	}
	file_svc_alert_v1_service_proto_msgTypes[20].OneofWrappers = []any{
		(*UpdateAlertGroupRequest_Mutation_SetName)(nil),
		(*UpdateAlertGroupRequest_Mutation_SetInterval)(nil),
		(*UpdateAlertGroupRequest_Mutation_SetQueryOffset)(nil),
		(*UpdateAlertGroupRequest_Mutation_SetLimit)(nil),
		(*UpdateAlertGroupRequest_Mutation_SetLabels)(nil),
	}
	file_svc_alert_v1_service_proto_msgTypes[22].OneofWrappers = []any{
		(*UpdateAlertRuleRequest_Mutation_SetName)(nil),
		(*UpdateAlertRuleRequest_Mutation_SetExpr)(nil),
		(*UpdateAlertRuleRequest_Mutation_SetLabels)(nil),
		(*UpdateAlertRuleRequest_Mutation_SetAnnotations)(nil),
		(*UpdateAlertRuleRequest_Mutation_SetFor)(nil),
		(*UpdateAlertRuleRequest_Mutation_SetKeepFiringFor)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_svc_alert_v1_service_proto_rawDesc), len(file_svc_alert_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svc_alert_v1_service_proto_goTypes,
		DependencyIndexes: file_svc_alert_v1_service_proto_depIdxs,
		MessageInfos:      file_svc_alert_v1_service_proto_msgTypes,
	}.Build()
	File_svc_alert_v1_service_proto = out.File
	file_svc_alert_v1_service_proto_goTypes = nil
	file_svc_alert_v1_service_proto_depIdxs = nil
}
