// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file svc/feature/v1/service.proto (package svc.feature.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AllowedUsageRequest, AllowedUsageResponse, HasFeatureRequest, HasFeatureResponse, ListFeatureRequest, ListFeatureResponse } from "./service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service svc.feature.v1.FeatureService
 */
export const FeatureService = {
  typeName: "svc.feature.v1.FeatureService",
  methods: {
    /**
     * @generated from rpc svc.feature.v1.FeatureService.HasFeature
     */
    hasFeature: {
      name: "HasFeature",
      I: HasFeatureRequest,
      O: HasFeatureResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc svc.feature.v1.FeatureService.ListFeature
     */
    listFeature: {
      name: "ListFeature",
      I: ListFeatureRequest,
      O: ListFeatureResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc svc.feature.v1.FeatureService.AllowedUsage
     */
    allowedUsage: {
      name: "AllowedUsage",
      I: AllowedUsageRequest,
      O: AllowedUsageResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

