// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file svc/localhost/v1/service.proto (package svc.localhost.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DoLoginRequest, DoLoginResponse, DoLogoutRequest, DoLogoutResponse, DoUpdateRequest, DoUpdateResponse, PingRequest, PingResponse } from "./service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service svc.localhost.v1.LocalhostService
 */
export const LocalhostService = {
  typeName: "svc.localhost.v1.LocalhostService",
  methods: {
    /**
     * @generated from rpc svc.localhost.v1.LocalhostService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc svc.localhost.v1.LocalhostService.DoLogin
     */
    doLogin: {
      name: "DoLogin",
      I: DoLoginRequest,
      O: DoLoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc svc.localhost.v1.LocalhostService.DoLogout
     */
    doLogout: {
      name: "DoLogout",
      I: DoLogoutRequest,
      O: DoLogoutResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc svc.localhost.v1.LocalhostService.DoUpdate
     */
    doUpdate: {
      name: "DoUpdate",
      I: DoUpdateRequest,
      O: DoUpdateResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

