// @generated by protoc-gen-connect-query v2.1.1 with parameter "target=ts,import_extension=none"
// @generated from file svc/organization/v1/service.proto (package svc.organization.v1, syntax proto3)
/* eslint-disable */

import { OrganizationService } from "./service_pb";

/**
 * @generated from rpc svc.organization.v1.OrganizationService.CreateEnvironment
 */
export const createEnvironment = OrganizationService.method.createEnvironment;

/**
 * @generated from rpc svc.organization.v1.OrganizationService.GetEnvironment
 */
export const getEnvironment = OrganizationService.method.getEnvironment;

/**
 * @generated from rpc svc.organization.v1.OrganizationService.ListEnvironment
 */
export const listEnvironment = OrganizationService.method.listEnvironment;

/**
 * @generated from rpc svc.organization.v1.OrganizationService.ListUser
 */
export const listUser = OrganizationService.method.listUser;

/**
 * @generated from rpc svc.organization.v1.OrganizationService.InviteUser
 */
export const inviteUser = OrganizationService.method.inviteUser;

/**
 * @generated from rpc svc.organization.v1.OrganizationService.RevokeUserInvitation
 */
export const revokeUserInvitation = OrganizationService.method.revokeUserInvitation;

/**
 * @generated from rpc svc.organization.v1.OrganizationService.ListUserInvitation
 */
export const listUserInvitation = OrganizationService.method.listUserInvitation;

/**
 * @generated from rpc svc.organization.v1.OrganizationService.CreateAddonSubscription
 */
export const createAddonSubscription = OrganizationService.method.createAddonSubscription;

/**
 * @generated from rpc svc.organization.v1.OrganizationService.ListAddonSubscription
 */
export const listAddonSubscription = OrganizationService.method.listAddonSubscription;

/**
 * @generated from rpc svc.organization.v1.OrganizationService.RemoveAddonSubscription
 */
export const removeAddonSubscription = OrganizationService.method.removeAddonSubscription;

/**
 * payment
 *
 * @generated from rpc svc.organization.v1.OrganizationService.GetStripePublishableKey
 */
export const getStripePublishableKey = OrganizationService.method.getStripePublishableKey;

/**
 * @generated from rpc svc.organization.v1.OrganizationService.GetStripeBillingPortal
 */
export const getStripeBillingPortal = OrganizationService.method.getStripeBillingPortal;

/**
 * @generated from rpc svc.organization.v1.OrganizationService.CreateStripeCustomerSession
 */
export const createStripeCustomerSession = OrganizationService.method.createStripeCustomerSession;

/**
 * @generated from rpc svc.organization.v1.OrganizationService.ListPaymentMethod
 */
export const listPaymentMethod = OrganizationService.method.listPaymentMethod;
