// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file svc/environment/v1/service.proto (package svc.environment.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListMachineRequest, ListMachineResponse } from "./service_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service svc.environment.v1.EnvironmentService
 */
export const EnvironmentService = {
  typeName: "svc.environment.v1.EnvironmentService",
  methods: {
    /**
     * @generated from rpc svc.environment.v1.EnvironmentService.ListMachine
     */
    listMachine: {
      name: "ListMachine",
      I: ListMachineRequest,
      O: ListMachineResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

